### ISSUE TITLE
Failed to build the environment with docker-buildenv-raspbian.sh

### ISSUE THREAD

**Issue by modlfo** [hexdump0815/rack-dockerbuild-v2#1]
Hi,

I tried to build this on my RPi 4 but I ran into problems when trying to create the build environments for raspbian.

```    leonardo@raspberrypi:~/rack-dockerbuild-v2 $ ./docker-buildenv-raspbian.sh 
    E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
    E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
    E: debootstrap can only run as root
    sha256:b5985e5e7b14f77b63cda9d1591ffdc2e3f445b12d615f79543fe88230bf6461
    Sending build context to Docker daemon  2.048kB
    Step 1/3 : FROM raspbian-bullseye
     ---> b5985e5e7b14
    Step 2/3 : RUN apt-get update
     ---> Running in bdacf781564f
    failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```

I tried running with `sudo` so `debootstrap` is called but I got the following error:

```    E: Invalid Release file, no entry for main/binary-arm64/Packages
    sha256:574765e85e1a8fc6fe4cd1af60bcb377b0667ba75b29321e51931857f4617a85
    Sending build context to Docker daemon  2.048kB
    Step 1/3 : FROM raspbian-bullseye
     ---> 574765e85e1a
    Step 2/3 : RUN apt-get update
     ---> Running in b76073174bf2
    failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
``` 
Do you know how can I fix this? I looks like building with the ubuntu image works.

**Comment by modlfo** [comment]
I forgot to mention that I'm running Raspbian 64 bit in the RPi 4.

**Comment by hexdump0815** [comment]
@modlfo - that looks a bit like docker is not working well - i never used it on raspbian directly and thus do not know if docker is working well there out of the box or not - maybe a google search on docker setup and potential problems on raspbian might bring something up?

**Comment by modlfo** [comment]
I managed to build using the ubuntu container on top of Raspbian 64 bit. 

Could it be that `debootstrap` only works with Raspbian 32 bit? It looks like http://archive.raspbian.org/raspbian only has `armhf` packages.

In any case, I got it working using ` ./docker-buildenv.sh`.

**Comment by hexdump0815** [comment]
i think raspbian 64bit is essentially debian while 32bit is a self maintained repo by the raspberry pi team ... happy to hear that you got it working
